name: Deploy Backend to Cloud Run

env:
  SERVICE_NAME: ai-addy-backend
  REGION: us-central1
  ARTIFACT_REGISTRY: addy-ai-backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 🏗️
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      - name: Build and Push Docker Image
        env:
          API_URL: ${{ secrets.API_URL }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          docker build \
            --build-arg API_URL=$API_URL \
            --build-arg BUCKET_NAME=$BUCKET_NAME \
            --build-arg PROJECT_ID=$PROJECT_ID \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --set-env-vars "API_URL=${{ secrets.API_URL }}" \
            --allow-unauthenticated
