name: Deploy Backend to Cloud Run

env:
  SERVICE_NAME: ai-addy-backend 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 🏗️
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Build and Push Docker Image
        env:
          API_URL: ${{ secrets.API_URL }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          docker build \
            --build-arg API_URL=$API_URL \
            --build-arg BUCKET_NAME=$BUCKET_NAME \
            --build-arg PROJECT_ID=$PROJECT_ID \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/addy-ai-backend/${{ secrets.DOCKER_IMAGE_NAME }}:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/addy-ai-backend/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/addy-ai-backend/${{ secrets.DOCKER_IMAGE_NAME }}:latest \
            --platform managed \
            --region us-central1 \
            --set-env-vars "API_URL=${{ secrets.API_URL }},BUCKET_NAME=${{ secrets.BUCKET_NAME }},PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --allow-unauthenticated \
            --verbosity=debug
